name: Unit testing
on:
  push
jobs:
  run-tracker:
    runs-on: ubuntu-latest
  
    steps:
      - name: Setup
        uses: setup

      - name: yarn start
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn start --source tesla-website
