name: Track changes
on:
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    # https://crontab.guru/#0_*/6_*_*_*
    - cron:  '0 */6 * * *'
jobs:
  run-tracker:
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Yarn install
        run: |
          yarn
      - name: setup git config
        run: |
          # setup the username and email
          git config user.name "Tesla Tracker"
          git config user.email "<>"
      - name: yarn start
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          yarn start
